#!/bin/bash
# =============================================================================
# Anti-Theft Smart System — One-shot bootstrap for production deployment
#
# Generates:
#   1. Self-signed TLS certificates (CA + server) — NEVER expire (36500 days)
#   2. MQTT credentials (backend + 10 edge devices) with hashed passwd file
#   3. Production .env file with all secrets pre-filled
#
# Usage:
#   chmod +x bootstrap.sh
#   ./bootstrap.sh [SERVER_IP_OR_HOSTNAME] [NUM_DEVICES]
#
# After running:
#   docker compose up -d
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVER_CN="${1:-$(hostname -I 2>/dev/null | awk '{print $1}' || echo '127.0.0.1')}"
NUM_DEVICES="${2:-10}"
DAYS=36500  # ~100 years — never expire

echo "============================================"
echo " Anti-Theft Smart System — Bootstrap"
echo "============================================"
echo " Server:      ${SERVER_CN}"
echo " Devices:     ${NUM_DEVICES}"
echo " Cert expiry: ${DAYS} days (~100 years)"
echo "============================================"
echo ""

# -------------------------------------------------------
# 1. TLS Certificates
# -------------------------------------------------------
CERT_DIR="${SCRIPT_DIR}/certs"
mkdir -p "$CERT_DIR"

echo "[1/3] Generating TLS certificates..."

# CA key and cert
openssl genrsa -out "$CERT_DIR/ca.key" 4096 2>/dev/null
openssl req -new -x509 -days "$DAYS" -key "$CERT_DIR/ca.key" \
    -out "$CERT_DIR/ca.crt" \
    -subj "/CN=FarmGuard CA/O=FarmGuard/C=IN" 2>/dev/null

# Server key and CSR
openssl genrsa -out "$CERT_DIR/server.key" 4096 2>/dev/null
openssl req -new -key "$CERT_DIR/server.key" \
    -out "$CERT_DIR/server.csr" \
    -subj "/CN=${SERVER_CN}/O=FarmGuard/C=IN" 2>/dev/null

# Server SAN config (IP + DNS)
cat > "$CERT_DIR/_server_ext.cnf" <<EOF
[v3_req]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
IP.1 = ${SERVER_CN}
IP.2 = 127.0.0.1
DNS.1 = localhost
DNS.2 = mosquitto
DNS.3 = minio
DNS.4 = backend
EOF

# Sign server cert with CA
openssl x509 -req -in "$CERT_DIR/server.csr" \
    -CA "$CERT_DIR/ca.crt" -CAkey "$CERT_DIR/ca.key" -CAcreateserial \
    -out "$CERT_DIR/server.crt" -days "$DAYS" \
    -extfile "$CERT_DIR/_server_ext.cnf" -extensions v3_req 2>/dev/null

# Cleanup intermediate files
rm -f "$CERT_DIR/server.csr" "$CERT_DIR/_server_ext.cnf" "$CERT_DIR/ca.srl"

echo "  CA cert:     ${CERT_DIR}/ca.crt"
echo "  Server cert: ${CERT_DIR}/server.crt"
echo "  Server key:  ${CERT_DIR}/server.key"
echo ""

# -------------------------------------------------------
# 2. MQTT Credentials
# -------------------------------------------------------
MQTT_DIR="${SCRIPT_DIR}/mosquitto"
CREDS_DIR="${MQTT_DIR}/credentials"
PASSWD_FILE="${MQTT_DIR}/passwd"

mkdir -p "$CREDS_DIR"

echo "[2/3] Generating MQTT credentials..."

# Backend MQTT user
BACKEND_MQTT_PASS=$(openssl rand -hex 16)
echo "backend_svc:${BACKEND_MQTT_PASS}" > "$PASSWD_FILE"

cat > "$CREDS_DIR/backend.env" <<EOF
MQTT_USERNAME=backend_svc
MQTT_PASSWORD=${BACKEND_MQTT_PASS}
EOF
echo "  [backend_svc] → credentials/backend.env"

# Per-device MQTT users
for i in $(seq 1 "$NUM_DEVICES"); do
    DEVICE_ID=$(printf "FARM-%03d" "$i")
    DEVICE_PASS=$(openssl rand -hex 16)
    echo "${DEVICE_ID}:${DEVICE_PASS}" >> "$PASSWD_FILE"

    cat > "$CREDS_DIR/${DEVICE_ID}.env" <<EOF
MQTT_USERNAME=${DEVICE_ID}
MQTT_PASSWORD=${DEVICE_PASS}
EOF
    echo "  [${DEVICE_ID}] → credentials/${DEVICE_ID}.env"
done

# Hash passwords using mosquitto_passwd if available
if command -v mosquitto_passwd &>/dev/null; then
    mosquitto_passwd -U "$PASSWD_FILE"
    echo "  Password file hashed locally."
else
    echo "  NOTE: mosquitto_passwd not found locally — will hash inside Docker."
    echo "  After 'docker compose up', run:"
    echo "    docker exec \$(docker ps -qf name=mosquitto) mosquitto_passwd -U /mosquitto/config/passwd"
    echo "    docker restart \$(docker ps -qf name=mosquitto)"
fi
echo ""

# -------------------------------------------------------
# 3. Production .env
# -------------------------------------------------------
ENV_FILE="${SCRIPT_DIR}/.env"

echo "[3/3] Generating production .env..."

POSTGRES_PASS=$(openssl rand -hex 16)
MINIO_ACCESS=$(openssl rand -hex 16)
MINIO_SECRET=$(openssl rand -hex 32)
JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || openssl rand -base64 32)

cat > "$ENV_FILE" <<EOF
# =============================================================================
# Anti-Theft Smart System — Production Environment
# Generated by bootstrap.sh on $(date -Iseconds)
# =============================================================================

ENV=production

# Database
POSTGRES_USER=farm_user
POSTGRES_PASSWORD=${POSTGRES_PASS}
POSTGRES_DB=farm_surveillance
DATABASE_URL=postgresql://farm_user:${POSTGRES_PASS}@postgres:5432/farm_surveillance

# MQTT
MQTT_BROKER=mosquitto
MQTT_PORT=1883
MQTT_USERNAME=backend_svc
MQTT_PASSWORD=${BACKEND_MQTT_PASS}

# MinIO (S3-compatible object storage)
MINIO_ENDPOINT=minio:9000
MINIO_ACCESS_KEY=${MINIO_ACCESS}
MINIO_SECRET_KEY=${MINIO_SECRET}
MINIO_BUCKET=alert-snapshots
MINIO_SECURE=false

# JWT
JWT_SECRET_KEY=${JWT_SECRET}
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=43200

# Firebase Cloud Messaging
FIREBASE_CREDENTIALS_PATH=firebase-admin-key.json

# Server
HOST=0.0.0.0
PORT=8000

# CORS — add your domain(s) here, comma-separated
# Example: https://api.farmguard.in,https://admin.farmguard.in
CORS_ORIGINS=
EOF

echo "  .env written to ${ENV_FILE}"
echo ""

# -------------------------------------------------------
# Summary
# -------------------------------------------------------
echo "============================================"
echo " Bootstrap complete!"
echo "============================================"
echo ""
echo " Certificates (never expire):"
echo "   ${CERT_DIR}/ca.crt"
echo "   ${CERT_DIR}/server.crt"
echo "   ${CERT_DIR}/server.key"
echo ""
echo " MQTT credentials:"
echo "   ${PASSWD_FILE}"
echo "   ${CREDS_DIR}/backend.env"
echo "   ${CREDS_DIR}/FARM-001.env ... FARM-$(printf '%03d' "$NUM_DEVICES").env"
echo ""
echo " Environment:"
echo "   ${ENV_FILE}"
echo ""
echo " Next steps:"
echo "   1. Place firebase-admin-key.json in ${SCRIPT_DIR}/"
echo "   2. docker compose up -d"
echo "   3. Provision devices:  curl -X POST https://${SERVER_CN}/api/v1/admin/devices/provision \\"
echo "        -H 'Content-Type: application/json' -d '{\"device_uid\": \"FARM-001\"}'"
echo "   4. Copy to each Pi:"
echo "        scp ${CERT_DIR}/ca.crt pi@<PI_IP>:/opt/surveillance/certs/"
echo "        scp ${CREDS_DIR}/FARM-001.env pi@<PI_IP>:/opt/surveillance/config/"
echo ""
